[package]
name = "my-ecs-macros"
version = "0.1.1"
edition = "2021"
rust-version = "1.65"
repository = "https://github.com/ecoricemon/my-ecs"
license = "Apache-2.0 OR MIT"
description = "Procedural macros for my-ecs components, entities, resources, filters, and requests"
keywords = ["ecs"]

[lib]
proc-macro = true
doctest = false

[dependencies]
syn = { workspace = true, features = [
  "full",
  "derive",
  "extra-traits"
]}
proc-macro2 = { workspace = true }
quote = { workspace = true }
