//! ECS core module.

pub(crate) mod cache;
pub(crate) mod cmd;
pub(crate) mod ent;
pub(crate) mod entry;
pub(crate) mod lock;
pub(crate) mod post;
pub(crate) mod resource;
pub(crate) mod sched;
pub(crate) mod stat;
pub(crate) mod sys;
pub(crate) mod wait;
pub(crate) mod web;
pub(crate) mod worker;

pub mod prelude {
    pub use super::{
        cmd::prelude::*,
        ent::prelude::*,
        entry::prelude::*,
        post::prelude::*,
        resource::prelude::*,
        sched::prelude::*,
        sys::prelude::*,
        worker::prelude::*,
        {DynResult, EcsError},
    };
}

use std::{error::Error, fmt};
use thiserror::Error;

/// A [`Result`] with super flexible error type `Box<dyn Error + Send + Sync + 'static>`.
pub type DynResult<T> = Result<T, Box<dyn Error + Send + Sync + 'static>>;

/// An error generated by ECS instance.
#[derive(Error)]
#[repr(C)]
pub enum EcsError<Data = ()> {
    /// A requested system does not exist.
    #[error("unknown system `{0}`")]
    UnknownSystem(String, Data),

    /// A requested entity does not exist.
    #[error("unknown entity `{0}`")]
    UnknownEntity(String, Data),
    /// An entity request is invalid.
    #[error("invalid entity `{0}`")]
    InvalidEntity(String, Data),

    /// A requested resource does not exist.
    #[error("unknown resource `{0}`")]
    UnknownResource(String, Data),
    /// A resource is already registered.
    #[error("duplicated resource `{0}`")]
    DupResource(String, Data),

    /// A system request is invalid.
    #[error("invalid request `{0}`")]
    InvalidRequest(String, Data),

    /// An uncategorized ECS error.
    #[error("unknown error `{0}`")]
    Unknown(String, Data),
}

impl<Data> fmt::Debug for EcsError<Data> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnknownSystem(reason, ..) => {
                write!(f, "EcsError::UnknownSystem({reason}, ..)")
            }
            Self::UnknownEntity(reason, ..) => {
                write!(f, "EcsError::UnknownEntity({reason}, ..)")
            }
            Self::InvalidEntity(reason, ..) => {
                write!(f, "EcsError::InvalidEntity({reason}, ..)")
            }
            Self::UnknownResource(reason, ..) => {
                write!(f, "EcsError::UnknownResource({reason}, ..)")
            }
            Self::DupResource(reason, ..) => {
                write!(f, "EcsError::DupResource({reason}, ..)")
            }
            Self::InvalidRequest(reason, ..) => {
                write!(f, "EcsError::InvalidRequest({reason}, ..)")
            }
            Self::Unknown(reason, ..) => {
                write!(f, "EcsError::Unknown({reason}, ..)")
            }
        }
    }
}

impl<Data> EcsError<Data> {
    /// Returns the human-readable reason string.
    pub fn reason(&self) -> &str {
        match self {
            Self::UnknownSystem(reason, ..) => reason,
            Self::UnknownEntity(reason, ..) => reason,
            Self::InvalidEntity(reason, ..) => reason,
            Self::UnknownResource(reason, ..) => reason,
            Self::DupResource(reason, ..) => reason,
            Self::InvalidRequest(reason, ..) => reason,
            Self::Unknown(reason, ..) => reason,
        }
    }

    /// Consumes the error and returns its attached data.
    pub fn take_data(self) -> Data {
        match self {
            Self::UnknownSystem(_, data) => data,
            Self::UnknownEntity(_, data) => data,
            Self::InvalidEntity(_, data) => data,
            Self::UnknownResource(_, data) => data,
            Self::DupResource(_, data) => data,
            Self::InvalidRequest(_, data) => data,
            Self::Unknown(_, data) => data,
        }
    }

    /// Removes the attached data from the error.
    pub fn without_data(self) -> EcsError<()> {
        self.with_data(())
    }

    /// Replaces the attached data with `data`.
    pub fn with_data<OutData>(self, data: OutData) -> EcsError<OutData> {
        self.map_data(|_| data)
    }

    /// Maps the attached data while preserving the error kind and reason.
    pub fn map_data<F, OutData>(self, f: F) -> EcsError<OutData>
    where
        F: FnOnce(Data) -> OutData,
    {
        match self {
            Self::UnknownSystem(reason, old) => EcsError::UnknownSystem(reason, f(old)),
            Self::UnknownEntity(reason, old) => EcsError::UnknownEntity(reason, f(old)),
            Self::InvalidEntity(reason, old) => EcsError::InvalidEntity(reason, f(old)),
            Self::UnknownResource(reason, old) => EcsError::UnknownResource(reason, f(old)),
            Self::DupResource(reason, old) => EcsError::DupResource(reason, f(old)),
            Self::InvalidRequest(reason, old) => EcsError::InvalidRequest(reason, f(old)),
            Self::Unknown(reason, old) => EcsError::Unknown(reason, f(old)),
        }
    }
}
