//! ECS core module.

pub(crate) mod cache;
pub(crate) mod cmd;
pub(crate) mod ent;
pub(crate) mod entry;
pub(crate) mod lock;
pub(crate) mod post;
pub(crate) mod resource;
pub(crate) mod sched;
pub(crate) mod sys;
pub(crate) mod wait;
pub(crate) mod web;
pub(crate) mod worker;

pub mod prelude {
    pub use super::{
        cmd::prelude::*,
        ent::prelude::*,
        entry::prelude::*,
        post::prelude::*,
        resource::prelude::*,
        sched::prelude::*,
        sys::prelude::*,
        worker::prelude::*,
        {DynResult, EcsError},
    };
}

use std::{error::Error, fmt};
use thiserror::Error;

/// A [`Result`] with super flexible error type `Box<dyn Error + Send + Sync + 'static>`.
pub type DynResult<T> = Result<T, Box<dyn Error + Send + Sync + 'static>>;

/// An error generated by ECS instance.
#[derive(Error)]
#[repr(C)]
pub enum EcsError<Data = ()> {
    /// A requested system does not exist.
    #[error("unknown system `{0}`")]
    UnknownSystem(String, Data),

    /// A requested entity does not exist.
    #[error("unknown entity `{0}`")]
    UnknownEntity(String, Data),
    /// An entity request is invalid.
    #[error("invalid entity `{0}`")]
    InvalidEntity(String, Data),

    /// A requested resource does not exist.
    #[error("unknown resource `{0}`")]
    UnknownResource(String, Data),
    /// A resource is already registered.
    #[error("duplicated resource `{0}`")]
    DupResource(String, Data),

    /// A system request is invalid.
    #[error("invalid request `{0}`")]
    InvalidRequest(String, Data),

    /// An uncategorized ECS error.
    #[error("unknown error `{0}`")]
    Unknown(String, Data),
}

impl<Data> fmt::Debug for EcsError<Data> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnknownSystem(reason, ..) => {
                write!(f, "EcsError::UnknownSystem({reason}, ..)")
            }
            Self::UnknownEntity(reason, ..) => {
                write!(f, "EcsError::UnknownEntity({reason}, ..)")
            }
            Self::InvalidEntity(reason, ..) => {
                write!(f, "EcsError::InvalidEntity({reason}, ..)")
            }
            Self::UnknownResource(reason, ..) => {
                write!(f, "EcsError::UnknownResource({reason}, ..)")
            }
            Self::DupResource(reason, ..) => {
                write!(f, "EcsError::DupResource({reason}, ..)")
            }
            Self::InvalidRequest(reason, ..) => {
                write!(f, "EcsError::InvalidRequest({reason}, ..)")
            }
            Self::Unknown(reason, ..) => {
                write!(f, "EcsError::Unknown({reason}, ..)")
            }
        }
    }
}

impl<Data> EcsError<Data> {
    /// Returns the human-readable reason string.
    pub fn reason(&self) -> &str {
        match self {
            Self::UnknownSystem(reason, ..) => reason,
            Self::UnknownEntity(reason, ..) => reason,
            Self::InvalidEntity(reason, ..) => reason,
            Self::UnknownResource(reason, ..) => reason,
            Self::DupResource(reason, ..) => reason,
            Self::InvalidRequest(reason, ..) => reason,
            Self::Unknown(reason, ..) => reason,
        }
    }

    /// Consumes the error and returns its attached data.
    pub fn take_data(self) -> Data {
        match self {
            Self::UnknownSystem(_, data) => data,
            Self::UnknownEntity(_, data) => data,
            Self::InvalidEntity(_, data) => data,
            Self::UnknownResource(_, data) => data,
            Self::DupResource(_, data) => data,
            Self::InvalidRequest(_, data) => data,
            Self::Unknown(_, data) => data,
        }
    }

    /// Removes the attached data from the error.
    pub fn without_data(self) -> EcsError<()> {
        self.with_data(())
    }

    /// Replaces the attached data with `data`.
    pub fn with_data<OutData>(self, data: OutData) -> EcsError<OutData> {
        self.map_data(|_| data)
    }

    /// Maps the attached data while preserving the error kind and reason.
    pub fn map_data<F, OutData>(self, f: F) -> EcsError<OutData>
    where
        F: FnOnce(Data) -> OutData,
    {
        match self {
            Self::UnknownSystem(reason, old) => EcsError::UnknownSystem(reason, f(old)),
            Self::UnknownEntity(reason, old) => EcsError::UnknownEntity(reason, f(old)),
            Self::InvalidEntity(reason, old) => EcsError::InvalidEntity(reason, f(old)),
            Self::UnknownResource(reason, old) => EcsError::UnknownResource(reason, f(old)),
            Self::DupResource(reason, old) => EcsError::DupResource(reason, f(old)),
            Self::InvalidRequest(reason, old) => EcsError::InvalidRequest(reason, f(old)),
            Self::Unknown(reason, old) => EcsError::Unknown(reason, f(old)),
        }
    }
}

/// Runtime counters used when the `stat` feature is enabled.
pub mod stat {
    use std::{cell::RefCell, sync::Arc};

    macro_rules! decl_counter {
        ($name:ident, $field:ident, $id:ident) => {
            paste::paste! {
                #[cfg(feature = "stat")]
                static $id: std::sync::atomic::AtomicIsize = std::sync::atomic::AtomicIsize::new(0);

                #[cfg(feature = "stat")]
                fn [<load_fallback_ $name>]() -> isize {
                    $id.load(std::sync::atomic::Ordering::Relaxed)
                }

                #[cfg(feature = "stat")]
                fn [<store_fallback_ $name>](value: isize) {
                    $id.store(value, std::sync::atomic::Ordering::Relaxed);
                }

                #[cfg(feature = "stat")]
                fn [<increase_fallback_ $name>]() {
                    $id.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                }

                /// Loads the current scoped counter value, or `-1` when `stat` is disabled.
                pub fn [<load _$name>]() -> isize {
                    #[cfg(feature = "stat")]
                    {
                        if let Some(value) = with_scoped_metrics(|metrics| metrics.[<load_ $name>]()) {
                            value
                        } else {
                            [<load_fallback_ $name>]()
                        }
                    }

                    #[cfg(not(feature = "stat"))]
                    { -1 }
                }

                /// Stores the current scoped counter value when `stat` is enabled.
                pub fn [<store _$name>](_value: isize) {
                    #[cfg(feature = "stat")]
                    {
                        if with_scoped_metrics(|metrics| metrics.[<store_ $name>](_value)).is_none() {
                            [<store_fallback_ $name>](_value);
                        }
                    }
                }

                /// Increments the current scoped counter when `stat` is enabled.
                pub fn [<increase _$name>]() {
                    #[cfg(feature = "stat")]
                    {
                        if with_scoped_metrics(|metrics| metrics.[<increase_ $name>]()).is_none() {
                            [<increase_fallback_ $name>]();
                        }
                    }
                }

                /// Asserts that the counter equals `_right` when `stat` is enabled.
                pub fn [<assert_eq _$name>](_right: isize) {
                    #[cfg(feature = "stat")]
                    { assert_eq!([<load _$name>](), _right); }
                }

                /// Asserts that the counter does not equal `_right` when `stat` is enabled.
                pub fn [<assert_ne _$name>](_right: isize) {
                    #[cfg(feature = "stat")]
                    { assert_ne!([<load _$name>](), _right); }
                }
            }
        };
    }

    macro_rules! decl_metric_methods {
        ($name:ident, $field:ident) => {
            paste::paste! {
                /// Loads the counter value, or `-1` when `stat` is disabled.
                pub fn [<load_ $name>](&self) -> isize {
                    #[cfg(feature = "stat")]
                    { self.$field.load(std::sync::atomic::Ordering::Relaxed) }

                    #[cfg(not(feature = "stat"))]
                    { -1 }
                }

                /// Stores the counter value when `stat` is enabled.
                pub fn [<store_ $name>](&self, _value: isize) {
                    #[cfg(feature = "stat")]
                    self.$field.store(_value, std::sync::atomic::Ordering::Relaxed);
                }

                /// Increments the counter when `stat` is enabled.
                pub fn [<increase_ $name>](&self) {
                    #[cfg(feature = "stat")]
                    self.$field.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                }

                /// Asserts that the counter equals `_right` when `stat` is enabled.
                pub fn [<assert_eq_ $name>](&self, _right: isize) {
                    #[cfg(feature = "stat")]
                    { assert_eq!(self.[<load_ $name>](), _right); }
                }

                /// Asserts that the counter does not equal `_right` when `stat` is enabled.
                pub fn [<assert_ne_ $name>](&self, _right: isize) {
                    #[cfg(feature = "stat")]
                    { assert_ne!(self.[<load_ $name>](), _right); }
                }
            }
        };
    }

    /// Per-ECS runtime counters.
    #[derive(Debug, Default)]
    pub struct RuntimeMetrics {
        #[cfg(feature = "stat")]
        system_task_count: std::sync::atomic::AtomicIsize,
        #[cfg(feature = "stat")]
        future_task_count: std::sync::atomic::AtomicIsize,
        #[cfg(feature = "stat")]
        parallel_task_count: std::sync::atomic::AtomicIsize,
    }

    impl RuntimeMetrics {
        decl_metric_methods!(system_task_count, system_task_count);
        decl_metric_methods!(future_task_count, future_task_count);
        decl_metric_methods!(parallel_task_count, parallel_task_count);
    }

    thread_local! {
        static CURRENT_METRICS: RefCell<Option<Arc<RuntimeMetrics>>> = const {
            RefCell::new(None)
        };
    }

    /// Runs `f` with `metrics` registered as the current thread's metrics target.
    pub(crate) fn with_current_metrics<R, F>(metrics: &Arc<RuntimeMetrics>, f: F) -> R
    where
        F: FnOnce() -> R,
    {
        let old = CURRENT_METRICS.with(|current| current.replace(Some(Arc::clone(metrics))));
        let _guard = CurrentMetricsGuard { old: Some(old) };
        f()
    }

    #[cfg(feature = "stat")]
    fn with_scoped_metrics<R, F>(f: F) -> Option<R>
    where
        F: FnOnce(&RuntimeMetrics) -> R,
    {
        CURRENT_METRICS.with(|current| current.borrow().as_deref().map(f))
    }

    struct CurrentMetricsGuard {
        old: Option<Option<Arc<RuntimeMetrics>>>,
    }

    impl Drop for CurrentMetricsGuard {
        fn drop(&mut self) {
            let old = self.old.take().unwrap();
            CURRENT_METRICS.with(|current| {
                current.replace(old);
            });
        }
    }

    decl_counter!(system_task_count, system_task_count, SYS_CNT);
    decl_counter!(future_task_count, future_task_count, FUT_CNT);
    decl_counter!(parallel_task_count, parallel_task_count, PAR_CNT);
}
